name: MineStrike
version: 1.0.2
main: cz.minestrike.me.limeth.minestrike.MineStrike
author: Limeth
depend: [StorageManager, WorldEdit]
commands:
    ms:
        description: MineStrike Administration Commands
    join:
        description: Join a MineStrike game
        aliases: [game, pripojit, spustit, hra]
    quit:
        description: Leave a MineStrike game
        aliases: [lobby, spawn, leave, odpojit, opustit]
    top:
        description: Shows the best players
        aliases: [nej, nejlepsi, zebricek]
